connection_internal: 1
control_internal: 0.05
hand_Valid: [ 1, 0 ]
task_name: "leap_motion_demo" #  self_check、test_by_hand 、 leap_motion_demo

self_check_angles1:
  - [60, 60, -10]
  - [60, 60, -10]
  - [60, 60, -10]
  - [60, 60, -10]
  - [60, 60, -10]

self_check_angles2:
  - [60, 60, 10]
  - [60, 60, 10]
  - [60, 60, 10]
  - [60, 60, 10]
  - [60, 30, 10]


hand_info:
  left_hand:
    ip: 127.0.0.1
    port: 10086
    lower_limits: 
    - [0, 0, -10]
    - [0, 0, -10]
    - [0, 0, -10]
    - [0, 0, -10]
    - [0, 0, -10]
    upper_limits: 
    - [90, 90, 10]
    - [90, 90, 10]
    - [90, 90, 10]
    - [90, 90, 10]
    - [90, 90, 10]
  right_hand:
    ip: 192.168.10.11
    port: 3335  


